---
# tasks file for ansible-role-install-packages
- name: Updating cache
  pacman:
    update-cache: true
  become: true

- name: "Install {{ install_what }}"
  pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ packages_list }}"
  become: true

